### ISSUE TITLE
7amboly

### ISSUE THREAD

**Issue by Applesx** [kofta999/senko_bot#4]
بسم الله
ابغي ميزة في البوت الخاص بك تجلعني اعدل علي الرسالة الي حد يرسلها لي السيرفر شات يعني انا اعمل ريبلاي علي الرسالة وأكتب باك سلاش الكوماند واشاور علي الرسالة الي هو كاتبها وابدلها بالكلمة الي مكتبها انا والبوت يبعت الرسالة

**Comment by Applesx** [comment]
شوف شغلك كويس

**Comment by kofta999** [comment]
خخخ اكتب يعلق

**Comment by kofta999** [comment]
no description = refused

**Comment by kofta999** [comment]
Impossible sadly
